### ISSUE TITLE
Bug problem!!!

### ISSUE THREAD

**Issue by WinJimLeon5953** [andywang425/BLTH#12]
have some change cannot use bilbibli evolved and Bilibili Live Tasks Helper at the same time，I can watch the Lives and the BLTH is working,but i can find & contorl the panel

**Comment by andywang425** [comment]
First, please ensure that you didn't hide the panel. You can hide or show the panel by clicking the button on the left side of the following button.  
Does BLTH work well when bilbibli evolved isn't Enabled?
I tested it for several times. The problem only arises when the network condition is poor. I will try to solve this problem.But I didn't find any connection between the bug and bilibili envolved.

**Comment by WinJimLeon5953** [comment]
Yes,i had done it when i wrote this problem.I never clicked the hide button ,when i refresh my website ,you can see the picture (like below PNG). I had ever aviod the bilibili evolved and BLTH can use normally.Thanks for your quick reply! Hope you to find this bug!
![PF`Q2LY)32B1Y1UR`A3KDRD](https://user-images.githubusercontent.com/16500142/89412542-dc853500-d759-11ea-99a4-9f203053c806.png)

**Comment by andywang425** [comment]
I updated the script just now. If the bug still remains, please open bilibili evolved's settings, click `Other`, change `Loading Mode `to `Delay`, and enable `Enable Ajax hook API`.  
Thanks for using BLTH! I'm sorry that the script doesn't support English because my English is poor and it will takes a lot of time and effort to support another language.
