### ISSUE TITLE
脚本入口消失（与bilibili evolved冲突）

### ISSUE THREAD

**Issue by Astesai** [andywang425/BLTH#156]
### 描述bug

脚本入口不见了 无法呼出面板

### 重现bug

刷新一下就这样了

### 预期行为

无

### 截图

![image](https://user-images.githubusercontent.com/67790796/128370019-8acf4881-979c-4b2a-a0b4-347bd25963fb.png)

### 运行日志

无

### 操作系统

win10

### 浏览器

chrome 92.0.4515.131

### 用户脚本管理器

tampermonkey 4.13

### 挂机助手版本

5.7.8.3

### 网络情况

一般

### 其他浏览器插件/脚本

bilibili evolved里的简化直播间功能 隐藏标题栏会把入口也一起隐藏

### 其他

建议：添加面板改为其他位置的选项

**Comment by kevinluo6188** [comment]
#157

**Comment by andywang425** [comment]
了解了，会想办法兼容。

**Comment by YimingZhanshen** [comment]
我并不认为是bilibili evolved的错误(我将所有插件和脚本除了'B站直播间挂机助手'全禁用也是这样)，应该是b站采取了相关措施，早期的版本也不行，所以应该不是作者大大的更新所导致的。值得一提的是脚本初次使用时可以正常弹出控制面板，但是我尝试用openMainWindow();函数尝试打开时却发现无法打开，不知道为什么。希望以上的描述能帮到作者大大修复这个bug

**Comment by Astesai** [comment]
> 我并不认为是bilibili evolved的错误(我将所有插件和脚本除了'B站直播间挂机助手'全禁用也是这样)，应该是b站采取了相关措施，早期的版本也不行，所以应该不是作者大大的更新所导致的。值得一提的是脚本初次使用时可以正常弹出控制面板，但是我尝试用openMainWindow();函数尝试打开时却发现无法打开，不知道为什么。希望以上的描述能帮到作者大大修复这个bug

确实 图中我单独开启挂机脚本也是没有入口 你这么一说大概率是B站限制了

**Comment by YimingZhanshen** [comment]
我回来了，脚本中的openMainWindow只是控制面板的初始化而已。我通过删除控制面板css的display成功让它现形了。
![image](https://user-images.githubusercontent.com/76594627/128393017-ea36a22c-795e-49de-b46e-db2ff74cf762.png)

**Comment by YimingZhanshen** [comment]
还有我觉得B站并没有采取针对性措施，只是由于界面的变动而导致脚本无法在合理的位置输出按钮罢了。

**Comment by YimingZhanshen** [comment]
emm看完群内小伙伴的留言基本可以确定是因为B站对界面的调整使部分直播间的按钮失效

**Comment by kevinluo6188** [comment]
测试过在游戏区没有，生活区没有 ---- 回复的原邮件 ***@***.***>发送日期2021年08月06日 01:55 ***@***.***> ***@***.******@***.***>主题Re: [andywang425/BLTH] 脚本入口消失（与bilibili evolved冲突） (#156)

emm看完群内小伙伴的留言基本可以确定是因为B站对界面的调整使部分直播间的按钮失效



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/andywang425/BLTH/issues/156#issuecomment-893665501",

"url": "https://github.com/andywang425/BLTH/issues/156#issuecomment-893665501",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by YimingZhanshen** [comment]
问题在$('.attention-btn-ctnr').append(btn);这句代码上，新版的直播界面中没有attention-btn-ctnr的div，所以导致按钮无法输出！

**Comment by YimingZhanshen** [comment]
在脚本编辑页面按Ctrl+F输入“// 初次运行时tips”然后在它前面加上“$('.follow-ctnr').append(btn);”即可解决！

**Comment by YimingZhanshen** [comment]
> 在脚本编辑页面按Ctrl+F输入“// 初次运行时tips”然后在它前面加上“$('.follow-ctnr').append(btn);”即可解决！

记得按Ctrl+S保存！

**Comment by Astesai** [comment]
> > 在脚本编辑页面按Ctrl+F输入“// 初次运行时tips”然后在它前面加上“$('.follow-ctnr').append(btn);”即可解决！
> 
> 记得按Ctrl+S保存！

您

**Comment by kevinluo6188** [comment]
您 ---- 回复的原邮件 ***@***.***>发送日期2021年08月06日 02:28 ***@***.***> ***@***.******@***.***>主题Re: [andywang425/BLTH] 脚本入口消失（与bilibili evolved冲突） (#156)



在脚本编辑页面按Ctrl+F输入“// 初次运行时tips”然后在它前面加上“$('.follow-ctnr').append(btn);”即可解决！



记得按Ctrl+S保存！



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/andywang425/BLTH/issues/156#issuecomment-893686137",

"url": "https://github.com/andywang425/BLTH/issues/156#issuecomment-893686137",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by andywang425** [comment]
> 问题在$('.attention-btn-ctnr').append(btn);这句代码上，新版的直播界面中没有attention-btn-ctnr的div，所以导致按钮无法输出！

我这还有`attention-btn-ctnr`这个div，并且没有`follow-ctnr`这个类，就很奇怪。。。  
和bilibili evolved的冲突确实是有的，把`简化直播间`中的`标题栏活动`关掉后，标题栏就会变成弹性布局导致关注按钮和脚本的按钮都不显示。  
大佬有空的话能否发个pr？因为我这边按钮可以正常显示所以不方便改。

**Comment by andywang425** [comment]
我想再问下按钮显示不出来的各位：脚本开始运行后是否会在右上角出现红色提示`必要页面元素缺失，强制运行（可能会看不到控制面板，提示信息）`？

**Comment by Astesai** [comment]
> 我想再问下按钮显示不出来的各位：脚本开始运行后是否会在右上角出现红色提示`必要页面元素缺失，强制运行（可能会看不到控制面板，提示信息）`？

不会

**Comment by konglinSoul** [comment]
> 我想再问下按钮显示不出来的各位：脚本开始运行后是否会在右上角出现红色提示`必要页面元素缺失，强制运行（可能会看不到控制面板，提示信息）`？

不会，我有三个账号，在我看的两个唱见直播间里，一个账号是正常显示按钮的，另外两个是不显示的，加上了$('.follow-ctnr').append(btn)；之后另外两个账号就会在粉丝团数量的右边显示按钮（正常的是在左边）。在官方lol直播间（6号直播间）三个账号都是正常显示按钮的。

不显示按钮的账号在唱见直播间里会有一个报错：
Uncaught TypeError: Cannot convert undefined or null to object
    at keys (<anonymous>)
    at t.report (bilibili.5e97f22406dc76555254.js:2)

**Comment by kevinluo6188** [comment]
> 我想再问下按钮显示不出来的各位：脚本开始运行后是否会在右上角出现红色提示`必要页面元素缺失，强制运行（可能会看不到控制面板，提示信息）`？

Uncaught TypeError: Cannot convert undefined or null to object
    at keys (<anonymous>)
    at t.report (bilibili.5e97f22406dc76555254.js:2)

**Comment by dong-jpg** [comment]
8月10日下午脚本已更新至5.7.8.4版本，出现“控制面板按钮消失问题”的可以更新至最新版本看一下，aw对这个bug进行了尝试修复，仍有问题的可以之后反馈。

**Comment by andywang425** [comment]
与bilibili evolved的冲突还没解决，但是由于新版直播间导致的按钮不显示bug已经修复了。
