### ISSUE TITLE
代码无法运行，提示  获取粉丝勋章列表失败 用户不存在 部分功能将无法正常运行

### ISSUE THREAD

**Issue by qqtqfs** [andywang425/BLTH#202]
### 描述bug

各个直播间打开都是  获取粉丝勋章列表失败 用户不存在 部分功能将无法正常运行
切换浏览区无用

### 重现bug

1.进入直播间
2.显示  获取粉丝勋章列表失败 用户不存在 部分功能将无法正常运行

### 预期行为

无

### 截图

![QQ截图20220101211016](https://user-images.githubusercontent.com/37046018/147851329-28429073-f034-4d9e-81c8-de82aee20310.png)

### 运行日志

无

### 操作系统

win10

### 浏览器

所有

### 用户脚本管理器

tampermonkey4.13.6138

### 挂机助手版本

	5.7.9.4

### 网络情况

好

### 其他浏览器插件/脚本

adguard

**Comment by Erebus-qie** [comment]
yes,that happens me,too.

**Comment by oneole** [comment]
炸了

**Comment by Tsingyun** [comment]
+1

**Comment by yysy0025** [comment]
+1

**Comment by z11y11w** [comment]
+1

**Comment by UGRO-G** [comment]
+1

**Comment by fanyu-zy** [comment]
确实，炸了

**Comment by hejueyun** [comment]
Same problem here

**Comment by benaify** [comment]
+1

**Comment by jlower** [comment]
确实，炸了

**Comment by SaguruHakuba** [comment]
+1

**Comment by keivnluo6191** [comment]
+1

**Comment by badhunter233** [comment]
+1

**Comment by gsmabc** [comment]
+1

**Comment by keivnluo6191** [comment]
临时修复: https://greasyfork.org/zh-CN/scripts/437917-b站直播间挂机助手 ---- 回复的原邮件 ***@***.***>发送日期2022年01月02日 18:59 ***@***.***> ***@***.******@***.***>主题Re: [andywang425/BLTH] 代码无法运行，提示  获取粉丝勋章列表失败 用户不存在 部分功能将无法正常运行 (Issue #202)
+1

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/andywang425/BLTH/issues/202#issuecomment-1003697686",
"url": "https://github.com/andywang425/BLTH/issues/202#issuecomment-1003697686",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by szmarcos** [comment]
同+1，

**Comment by Tinpa** [comment]
11

**Comment by zx001115** [comment]
+1，蹲個解決方案

**Comment by keivnluo6191** [comment]
临时解决方案：https://greasyfork.org/zh-CN/scripts/437917-b站直播间挂机助手

**Comment by keivnluo6191** [comment]
#201

**Comment by zx001115** [comment]
It works. Thanks for reply.

**Comment by hejanward** [comment]
> 临时解决方案：[https://greasyfork.org/zh-CN/scripts/437917-b站直播间挂机助手](https://greasyfork.org/zh-CN/scripts/437917-b%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B)

还是不行
