### ISSUE TITLE
Support for non-login watching inside some room number / category

### ISSUE THREAD

**Issue by aon3ko** [andywang425/BLTH#496]
### 描述

![Screenshot_20240508_204958](https://github.com/andywang425/BLTH/assets/7828319/99c53375-e35d-47cb-ba14-622d76625e7d)

As you may know, there's some live can not be viewed if you aren't logged in. The image of live stream will appear at first and then disappear very quickly. So maybe there's a possibility to remove that kind of restriction I guess.

**Comment by ADJazzzz** [comment]
The official bilibili has been updated, now some live (like APEX) must be logged in to get the live feed.

**Comment by aon3ko** [comment]
I tried to block ```https://s1.hdslb.com/bfs/static/blive/blfe-live-room/static/js/app.33bcae1698c519adbc38.js``` and the steam continues playing without interrupts. So, for solving this problem, I think that we might to modify some function inside this script.

**Comment by andywang425** [comment]
I don't think there are many users who need this feature, after all, it's not that hard to login a bilibili account. And predictably, to do this feature would require fighting against some of the anti-cheat logic on bilibili, which would be a hard work.

By the way, modifying or hijacking a function in a js file is not easy since we usually don't have direct access to the variables in it.

**Comment by aon3ko** [comment]
Thank you for your reply and your great work on this useful project. Have a good day!
